trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'static-web-nginx'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Checkout@1

    - task: Docker@2
      inputs:
        containerRegistry: 'dgiiexam'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: RunContainer
    steps:
    - script: |
        docker run -d -p 8080:8080 $(imageName):latest
      displayName: 'Run Docker Container on Port 8080'
