trigger:
- main

pool:
  name: 'dgiiexam'

variables:
  imageName: 'static-web-nginx'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self

    - task: Docker@2
      inputs:
        containerRegistry: 'dgiiexam'  # <-- reemplaza con tu conexión real
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: 'saas-website-template/Dockerfile'
        tags: |
          latest

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: RunContainer
    steps:
    - script: |
        docker run -d -p 8080:8080 $(imageName):latest
      displayName: 'Run Docker Container on Port 8080'
